#### 整合freemarker
spring:
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        template-loader-path:
        - classpath:/templates
    application:
        name: app-mayikt-portal-web
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://192.168.79.131:8080/eureka
server:
  port: 8080
  
redis:
 hostname: 127.0.0.1
 port: 6379
 password:
 




